version: '2'

services:
  sibcoind:
    image: docker-sibcoind
    build: containers/sibcoin/.
    volumes:
      - "./data-sibcoind:/data/sibcoin"
    network_mode: "service:electrum-server-sib"
    depends_on:
      - electrum-server-sib
    command:
      - "-reindex"
      - "-rest"

  electrum-server-sib:
    image: electrum-server-sib
    build: containers/electrum-server/.
    container_name: electrum-container
    ports:
      - '50002:50001'
    volumes:
      - './electrum_data:/var/electrum-server'
      - '.:/app'
